# These are supported funding model platforms
sensingclues
sensingclues: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
sensingclues: # Replace with a single Patreon username
sensingclues: # Replace with a single Open Collective username
sensingclues: # Replace with a single Ko-fi username
sensingclues: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
sensingclues: # Replace with a single Community Bridge project-name e.g., cloud-foundry
sensingclues: # Replace with a single Liberapay username
sensingclues: # Replace with a single IssueHunt username
sensingclues: # Replace with a single Otechie username
'https://sensingclues.org': # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
